import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";

export default function Home() {
  const { data: breweries, isError } = trpc.breweries.list.useQuery({
    take: 25,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            flex: 1,
            flexDirection: "column",
          }}
        >
          {breweries &&
            breweries.map(({ name, website }) => (
              <div style={{ padding: 4 }}>
                <p>{name}</p>
                {website ? (
                  <a href={website} target={"_blank"}>
                    {website}
                  </a>
                ) : (
                  <p style={{ color: "red" }}>No website available</p>
                )}
              </div>
            ))}
        </div>
      </main>
    </>
  );
}
